plugins:
  rating_enabled:
    default: true
    client: true
  rating_show_topic_tip:
    default: true
    client: true
  rating_show_numeric_average:
    default: true
    client: true
  rating_show_count:
    default: false
    client: true
  rating_topic_average_enabled:
    client: true
    default: true
  rating_topic_list_average_enabled:
    client: true
    default: true
  rating_hide_except_own_entry:
    default: false
    client: true
